# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Github pages
remote_theme:     poole/hyde

# Setup
title:            Ahan
tagline:          'Personal Website'
description:      '~ Software Engineer<br>~ Data Scientist<br>~ Aspiring Entreupreneur'
url:              http://ahanm.github.io/PersonalWebsite
baseurl:          /

# Software Engineer, Data Scientist, Aspiring Entreupreneur
# A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Customized by <a href="https://twitter.com/mdo" target="_blank">@AhanM</a>.

author:
  name:           'Ahan Mukhopadhyay'
  url:            https://github.com/AhanM

paginate:         5

# Custom vars
version:          2.0.0
plugins:          [jekyll-paginate]

github:           [metadata]
  # repo:           https://github.com/AhanM/PersonalWebsite
